export type Language = "en" | "hi" | "ur";
export type TabId = "tasks" | "desk" | "setup" | "help";
export type GestureMode = "typing" | "mouse" | "scroll";

export interface ServerJob {
  id: string;
  type: string;
  reward: string;
  payload: string;
  hindTask: string;
  dataSizeKb: number;
}

export interface SubmittedWork {
  jobId: string;
  answer: string;
  workerName: string;
  timestamp: string;
  rewardValue: string;
}

export const KEYBOARD_KEYS = [
  "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P",
  "A", "S", "D", "F", "G", "H", "J", "K", "L",
  "Z", "X", "C", "V", "B", "N", "M",
];

export const FINGERS = [
  "L Thumb", "L Index", "L Middle", "L Ring", "L Little",
  "R Thumb", "R Index", "R Middle", "R Ring", "R Little",
];

export const fallbackJobs: ServerJob[] = [
  {
    id: "off-1",
    type: "translation",
    reward: "Rs 15",
    payload: "Translate: Digital work empowers mobile-only users.",
    hindTask: "Translate this English sentence into simple Hindi.",
    dataSizeKb: 0.1,
  },
  {
    id: "off-2",
    type: "annotation",
    reward: "Rs 20",
    payload: "Coordinates detected: X:10, Y:90. Is this a valid touch point?",
    hindTask: "Confirm whether these coordinates are valid. Answer yes or no.",
    dataSizeKb: 0.15,
  },
];

export const ui = {
  en: {
    appName: "4S",
    pocketTitle: "4S Desktop",
    pocketSubtitle: "In your pocket",
    ready: "4S ready",
    dataSaverOn: "Data saver on",
    cameraOnly: "Camera only",
    localOnly: "Local only",
    wingsReady: "Wings ready",
    subtitle: "A mobile-first desktop-style workspace for students.",
    earnings: "Today earnings",
    language: "Language",
    alert: "Your work can stay safe locally, even when the internet is unavailable.",
    jobsLoaded: "New lightweight tasks are loaded.",
    localJobs: "The network is slow, so local sample tasks are available.",
    nameSaved: "Name updated.",
    needAnswer: "Please write an answer before submitting.",
    submitted: "Work submitted. Reward:",
    savedOffline: "The internet is slow. Your work was saved locally:",
    scanDone: "scan complete. This finger can be assigned to a gesture.",
    allFingersReady: "All fingers are ready for 4S control.",
    standardMode: "Standard 4S mode is on.",
    lightMode: "Data Saver is on. Camera features will use light mode.",
    mobileEngine: "Mobile camera engine",
    prototype: "Prototype",
    engineNote: "In the real version, the camera will scan hand landmarks. This is the working UI prototype.",
    dataSaverButtonOn: "Data Saver On",
    dataSaverButtonOff: "4S Standard",
    wallMode: "Wall mode",
    floatMode: "Float",
    compactModeShort: "Compact",
    setupGuide: "Setup guide",
    scanButton: "Scan",
    minimize4s: "Minimize 4S",
    fingerScan: "10 finger scan",
    readyPercent: "ready",
    scanned: "scanned",
    tapToScan: "tap to scan",
    record: "Work record",
    submittedCount: "submitted",
    emptyRecord: "Your first completed task will appear here.",
    tabs: {
      tasks: "Tasks",
      desk: "4S Desk",
      setup: "Setup guide",
      help: "Help",
    },
    tasksTitle: "Today micro-tasks",
    tasksSubtitle: "Select a task, read the instruction, write an answer, then submit it.",
    refresh: "Refresh tasks",
    loading: "Loading...",
    selected: "Selected",
    select: "Select",
    selectedTask: "Selected task",
    taskData: "Task data",
    answerLabel: "Write your answer here",
    answerPlaceholder: "Example: translation, yes/no answer, or short response...",
    deskHint: "You can also type from the 4S Desk tab.",
    submit: "Submit work",
    wallPreview: "Wall display preview",
    wallPreviewText: "A mock laptop-style workspace projected from a mobile device.",
    scale: "Scale",
    desktopTitle: "4S Desktop",
    active: "active",
    currentTask: "Current task",
    chooseTask: "Select a task",
    wallTaskFallback: "Task data will appear here on the wall display.",
    typedAnswer: "Air typed answer",
    typeFallback: "Type with the air keyboard...",
    gestureMode: "Gesture mode",
    modes: {
      typing: "Finger typing",
      mouse: "Air mouse",
      scroll: "Scroll / zoom",
    },
    airMouseControl: "Air mouse control",
    xPosition: "X position",
    yPosition: "Y position",
    wallScale: "Wall display scale",
    workflowContinuity: "Workflow continuity",
    workflowNote: "Browsers pause camera gestures when a window is minimized. Use one of these modes to keep 4S useful while another app is open.",
    compactMode: "Compact controller",
    compactModeNote: "Keeps a small 4S controller on screen so students can work beside another app.",
    pipMode: "Floating Chrome/Edge controller",
    pipModeNote: "Shows only the ready keyboard in a floating browser window when supported.",
    popoutMode: "Open pop-out controller",
    popoutModeNote: "Opens a small companion window that can stay next to another app.",
    compactClose: "Close compact controller",
    pipOpened: "Floating 4S controller opened.",
    companionOpened: "4S companion controller opened in a separate window.",
    companionBlocked: "Popup was blocked. Allow popups for 4S and try again.",
    airKeyboard: "Air keyboard",
    airKeyboardNote: "After the 10-finger scan, these keys simulate typing on the wall display.",
    mode: "Mode",
    space: "Space",
    back: "Back",
    submitSide: "Submit side",
    setupTitle: "Set up 4S for wall work",
    setupSteps: [
      ["Scan fingers", "Tap Scan until your main fingers are ready for typing and pointer control."],
      ["Open Wall mode", "Keep the 4S Desk visible on the wall or shared display before switching apps."],
      ["Minimize 4S", "Use Minimize 4S to open a floating or compact controller for working beside another app."],
      ["Work with keyboard and mouse", "Use the floating keyboard, air mouse controls, and wall screen together like a simple desktop."],
    ],
    helpTitle: "What 4S is for",
    helpItems: [
      ["For students", "4S helps students practice desktop-style work from a mobile phone when a laptop is not affordable."],
      ["Coding practice", "Students can practice typing code, editing text, and using a workspace-like screen."],
      ["Air typing", "Finger movement can become virtual keyboard input in a real camera version."],
      ["Air mouse", "The index finger can act as a pointer, and pinch can become click."],
      ["Offline first", "Core practice screens and saved work can remain available without internet."],
      ["Creator", "4S concept and prototype by Aftab Ahmad Khan."],
    ],
  },
  hi: {
    appName: "4S",
    pocketTitle: "4S Desktop",
    pocketSubtitle: "In your pocket",
    ready: "4S तैयार",
    dataSaverOn: "डेटा सेवर चालू",
    cameraOnly: "Camera only",
    localOnly: "Local only",
    wingsReady: "Wings ready",
    subtitle: "स्टूडेंट्स के लिए मोबाइल से डेस्कटॉप जैसा वर्कस्पेस।",
    earnings: "आज की कमाई",
    language: "भाषा",
    alert: "इंटरनेट न होने पर भी आपका काम लोकल में सुरक्षित रह सकता है।",
    jobsLoaded: "नए हल्के टास्क लोड हो गए।",
    localJobs: "नेटवर्क धीमा है, इसलिए लोकल सैंपल टास्क उपलब्ध हैं।",
    nameSaved: "नाम अपडेट हो गया।",
    needAnswer: "सबमिट करने से पहले उत्तर लिखें।",
    submitted: "काम सबमिट हो गया। रिवॉर्ड:",
    savedOffline: "इंटरनेट धीमा है। आपका काम लोकल में सेव हो गया:",
    scanDone: "स्कैन पूरा हुआ। इस फिंगर को gesture assign किया जा सकता है।",
    allFingersReady: "All fingers are ready for 4S control.",
    standardMode: "Standard 4S mode चालू है।",
    lightMode: "Data Saver चालू है। Camera features light mode में रहेंगे।",
    mobileEngine: "मोबाइल कैमरा इंजन",
    prototype: "प्रोटोटाइप",
    engineNote: "Real version में camera hand landmarks scan करेगा। अभी यह working UI prototype है।",
    dataSaverButtonOn: "Data Saver On",
    dataSaverButtonOff: "4S Standard",
    wallMode: "Wall mode",
    floatMode: "Float",
    compactModeShort: "Compact",
    setupGuide: "Setup guide",
    scanButton: "Scan",
    minimize4s: "Minimize 4S",
    fingerScan: "10 finger scan",
    readyPercent: "तैयार",
    scanned: "स्कैन हुआ",
    tapToScan: "स्कैन करें",
    record: "काम का रिकॉर्ड",
    submittedCount: "सबमिट",
    emptyRecord: "पहला task complete होते ही यहाँ दिखाई देगा।",
    tabs: {
      tasks: "Tasks",
      desk: "4S Desk",
      setup: "Setup guide",
      help: "Help",
    },
    tasksTitle: "आज के micro-tasks",
    tasksSubtitle: "Task चुनें, instruction पढ़ें, answer लिखें, फिर submit करें।",
    refresh: "Tasks refresh करें",
    loading: "लोड हो रहा है...",
    selected: "Selected",
    select: "Select",
    selectedTask: "Selected task",
    taskData: "Task data",
    answerLabel: "अपना answer यहाँ लिखें",
    answerPlaceholder: "Example: translation, yes/no answer, या short response...",
    deskHint: "आप 4S Desk tab से भी type कर सकते हैं।",
    submit: "काम submit करें",
    wallPreview: "Wall display preview",
    wallPreviewText: "Mobile से projected laptop-style workspace का mock preview।",
    scale: "Scale",
    desktopTitle: "4S Desktop",
    active: "active",
    currentTask: "Current task",
    chooseTask: "Task चुनें",
    wallTaskFallback: "Task data wall display पर यहाँ दिखेगा।",
    typedAnswer: "Air typed answer",
    typeFallback: "Air keyboard से type करें...",
    gestureMode: "Gesture mode",
    modes: {
      typing: "Finger typing",
      mouse: "Air mouse",
      scroll: "Scroll / zoom",
    },
    airMouseControl: "Air mouse control",
    xPosition: "X position",
    yPosition: "Y position",
    wallScale: "Wall display scale",
    workflowContinuity: "Workflow continuity",
    workflowNote: "Browsers pause camera gestures when a window is minimized. Use one of these modes to keep 4S useful while another app is open.",
    compactMode: "Compact controller",
    compactModeNote: "Keeps a small 4S controller on screen so students can work beside another app.",
    pipMode: "Floating Chrome/Edge controller",
    pipModeNote: "Shows only the ready keyboard in a floating browser window when supported.",
    popoutMode: "Open pop-out controller",
    popoutModeNote: "Opens a small companion window that can stay next to another app.",
    compactClose: "Close compact controller",
    pipOpened: "Floating 4S controller opened.",
    companionOpened: "4S companion controller opened in a separate window.",
    companionBlocked: "Popup was blocked. Allow popups for 4S and try again.",
    airKeyboard: "Air keyboard",
    airKeyboardNote: "10-finger scan के बाद ये keys wall display पर typing simulate करती हैं।",
    mode: "Mode",
    space: "Space",
    back: "Back",
    submitSide: "Submit side",
    setupTitle: "Set up 4S for wall work",
    setupSteps: [
      ["Scan fingers", "Tap Scan until your main fingers are ready for typing and pointer control."],
      ["Open Wall mode", "Keep the 4S Desk visible on the wall or shared display before switching apps."],
      ["Minimize 4S", "Use Minimize 4S to open a floating or compact controller for working beside another app."],
      ["Work with keyboard and mouse", "Use the floating keyboard, air mouse controls, and wall screen together like a simple desktop."],
    ],
    helpTitle: "4S किसके लिए है",
    helpItems: [
      ["For students", "4S उन students की मदद करता है जो laptop afford नहीं कर पाते और mobile से desktop-style practice करना चाहते हैं।"],
      ["Coding practice", "Students code typing, text editing और workspace-like screen की practice कर सकते हैं।"],
      ["Air typing", "Real camera version में finger movement virtual keyboard input बन सकता है।"],
      ["Air mouse", "Index finger pointer बन सकता है और pinch click बन सकता है।"],
      ["Offline first", "Core practice screens और saved work बिना internet भी available रह सकते हैं।"],
      ["Creator", "4S concept and prototype by Aftab Ahmad Khan."],
    ],
  },
  ur: {
    appName: "4S",
    pocketTitle: "4S Desktop",
    pocketSubtitle: "In your pocket",
    ready: "4S تیار",
    dataSaverOn: "ڈیٹا سیور آن",
    cameraOnly: "Camera only",
    localOnly: "Local only",
    wingsReady: "Wings ready",
    subtitle: "طلبہ کے لیے موبائل سے ڈیسک ٹاپ جیسا ورک اسپیس۔",
    earnings: "آج کی کمائی",
    language: "زبان",
    alert: "انٹرنیٹ نہ ہو تب بھی آپ کا کام مقامی طور پر محفوظ رہ سکتا ہے۔",
    jobsLoaded: "نئے ہلکے ٹاسک لوڈ ہو گئے۔",
    localJobs: "نیٹ ورک سست ہے، اس لیے مقامی سیمپل ٹاسک دستیاب ہیں۔",
    nameSaved: "نام اپ ڈیٹ ہو گیا۔",
    needAnswer: "سبمٹ کرنے سے پہلے جواب لکھیں۔",
    submitted: "کام سبمٹ ہو گیا۔ ریوارڈ:",
    savedOffline: "انٹرنیٹ سست ہے۔ آپ کا کام مقامی طور پر محفوظ ہو گیا:",
    scanDone: "اسکین مکمل ہوا۔ اس انگلی کو gesture assign کیا جا سکتا ہے۔",
    allFingersReady: "All fingers are ready for 4S control.",
    standardMode: "Standard 4S mode آن ہے۔",
    lightMode: "Data Saver آن ہے۔ Camera features light mode میں رہیں گے۔",
    mobileEngine: "موبائل کیمرا انجن",
    prototype: "پروٹوٹائپ",
    engineNote: "Real version میں camera hand landmarks scan کرے گا۔ ابھی یہ working UI prototype ہے۔",
    dataSaverButtonOn: "Data Saver On",
    dataSaverButtonOff: "4S Standard",
    wallMode: "Wall mode",
    floatMode: "Float",
    compactModeShort: "Compact",
    setupGuide: "Setup guide",
    scanButton: "Scan",
    minimize4s: "Minimize 4S",
    fingerScan: "10 finger scan",
    readyPercent: "تیار",
    scanned: "اسکین ہوا",
    tapToScan: "اسکین کریں",
    record: "کام کا ریکارڈ",
    submittedCount: "سبمٹ",
    emptyRecord: "پہلا task complete ہوتے ہی یہاں دکھائی دے گا۔",
    tabs: {
      tasks: "Tasks",
      desk: "4S Desk",
      setup: "Setup guide",
      help: "Help",
    },
    tasksTitle: "آج کے micro-tasks",
    tasksSubtitle: "Task منتخب کریں، instruction پڑھیں، answer لکھیں، پھر submit کریں۔",
    refresh: "Tasks refresh کریں",
    loading: "لوڈ ہو رہا ہے...",
    selected: "Selected",
    select: "Select",
    selectedTask: "Selected task",
    taskData: "Task data",
    answerLabel: "اپنا answer یہاں لکھیں",
    answerPlaceholder: "Example: translation, yes/no answer, یا short response...",
    deskHint: "آپ 4S Desk tab سے بھی type کر سکتے ہیں۔",
    submit: "کام submit کریں",
    wallPreview: "Wall display preview",
    wallPreviewText: "Mobile سے projected laptop-style workspace کا mock preview۔",
    scale: "Scale",
    desktopTitle: "4S Desktop",
    active: "active",
    currentTask: "Current task",
    chooseTask: "Task منتخب کریں",
    wallTaskFallback: "Task data wall display پر یہاں دکھے گا۔",
    typedAnswer: "Air typed answer",
    typeFallback: "Air keyboard سے type کریں...",
    gestureMode: "Gesture mode",
    modes: {
      typing: "Finger typing",
      mouse: "Air mouse",
      scroll: "Scroll / zoom",
    },
    airMouseControl: "Air mouse control",
    xPosition: "X position",
    yPosition: "Y position",
    wallScale: "Wall display scale",
    workflowContinuity: "Workflow continuity",
    workflowNote: "Browsers pause camera gestures when a window is minimized. Use one of these modes to keep 4S useful while another app is open.",
    compactMode: "Compact controller",
    compactModeNote: "Keeps a small 4S controller on screen so students can work beside another app.",
    pipMode: "Floating Chrome/Edge controller",
    pipModeNote: "Shows only the ready keyboard in a floating browser window when supported.",
    popoutMode: "Open pop-out controller",
    popoutModeNote: "Opens a small companion window that can stay next to another app.",
    compactClose: "Close compact controller",
    pipOpened: "Floating 4S controller opened.",
    companionOpened: "4S companion controller opened in a separate window.",
    companionBlocked: "Popup was blocked. Allow popups for 4S and try again.",
    airKeyboard: "Air keyboard",
    airKeyboardNote: "10-finger scan کے بعد یہ keys wall display پر typing simulate کرتی ہیں۔",
    mode: "Mode",
    space: "Space",
    back: "Back",
    submitSide: "Submit side",
    setupTitle: "Set up 4S for wall work",
    setupSteps: [
      ["Scan fingers", "Tap Scan until your main fingers are ready for typing and pointer control."],
      ["Open Wall mode", "Keep the 4S Desk visible on the wall or shared display before switching apps."],
      ["Minimize 4S", "Use Minimize 4S to open a floating or compact controller for working beside another app."],
      ["Work with keyboard and mouse", "Use the floating keyboard, air mouse controls, and wall screen together like a simple desktop."],
    ],
    helpTitle: "4S کس کے لیے ہے",
    helpItems: [
      ["For students", "4S ان students کی مدد کرتا ہے جو laptop afford نہیں کر پاتے اور mobile سے desktop-style practice کرنا چاہتے ہیں۔"],
      ["Coding practice", "Students code typing, text editing اور workspace-like screen کی practice کر سکتے ہیں۔"],
      ["Air typing", "Real camera version میں finger movement virtual keyboard input بن سکتا ہے۔"],
      ["Air mouse", "Index finger pointer بن سکتا ہے اور pinch click بن سکتا ہے۔"],
      ["Offline first", "Core practice screens اور saved work بغیر internet بھی available رہ سکتے ہیں۔"],
      ["Creator", "4S concept and prototype by Aftab Ahmad Khan."],
    ],
  },
} as const;

export type UiText = (typeof ui)[Language];
